CREATE TABLE IF NOT EXISTS papers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  paper_id VARCHAR(1024) NOT NULL,
  arxiv_id VARCHAR(255) NOT NULL DEFAULT '',
  source VARCHAR(64) NOT NULL DEFAULT '',
  conference VARCHAR(64) NOT NULL,
  year SMALLINT UNSIGNED NOT NULL,
  subjects JSON NOT NULL,
  primary_subject VARCHAR(255) NOT NULL DEFAULT '',
  track VARCHAR(255) NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  authors JSON NOT NULL,
  authors_text TEXT NOT NULL,
  abstract MEDIUMTEXT NOT NULL,
  pdf_url TEXT NOT NULL,
  keywords JSON NOT NULL,
  keywords_text TEXT NOT NULL,
  entry_type VARCHAR(64) NOT NULL DEFAULT '',
  editor JSON NOT NULL,
  editor_text TEXT NOT NULL,
  booktitle TEXT NOT NULL,
  pages VARCHAR(255) NOT NULL DEFAULT '',
  publisher VARCHAR(255) NOT NULL DEFAULT '',
  doi VARCHAR(512) NOT NULL DEFAULT '',
  biburl TEXT NOT NULL,
  bibsource TEXT NOT NULL,
  source_file VARCHAR(1024) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_papers_conference_year_track (conference, year, track),
  KEY idx_papers_conference_year (conference, year),
  KEY idx_papers_year (year),
  KEY idx_papers_doi (doi(191)),
  FULLTEXT KEY ft_papers_search (title, abstract, authors_text, keywords_text)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
